# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build And Test On Localhost Then Deploy To Render

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Clone Github Repository
      uses: actions/checkout@v4
    - name: Use Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Replace the Back End Endpoint
      run: echo "export const settings = {host:'http://localhost:3030'}" > src/config.js
    - name: Start Front End On Localhost
      run: npm run start-fe &
    - name: Start Back End On Localhost
      run: npm run start-be &
    - name: Install Browsers
      run: npx playwright install
    - name: Run UI Tests
      run: npm run test-ui
  
  deploy_backend:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID_BE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true 

  deploy_frontend:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID_FE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true 
